name: portable_accounting
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  drift: ^2.28.0
  sqlite3_flutter_libs: ^0.5.37
  path_provider: ^2.1.5
  path: ^1.9.1
  get_it: ^8.0.3
  go_router: ^16.0.0
  pdf: ^3.11.3
  printing: ^5.14.2
  hydrated_bloc: ^10.1.1
  intl: any
  file_picker: ^10.2.0
  share_plus: ^11.0.0
  equatable: ^2.0.7
  fpdart: ^1.1.1
  drift_flutter: ^0.2.5
  fl_chart: ^1.0.0
  permission_handler: ^12.0.1
  json_annotation: ^4.9.0
  image_picker: ^1.1.2
  file_saver: ^0.3.1
  syncfusion_flutter_datagrid: ^30.1.41
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  freezed: ^3.1.0
  build_runner: ^2.5.4
  drift_dev: ^2.28.0
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/fonts/
